version: '3'

services:
  bot:
    image: ghcr.io/chasseur-de-succes/cds-bot:master
    restart: always
    networks:
      - bdd
    env_file:
      - .env
      - .bot.env
    depends_on:
      - mongodb
  feed:
    image: ghcr.io/chasseur-de-succes/cds-steam-feed:main
    restart: always
    networks:
      - bdd
    env_file:
      - .env
      - .feed.env
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    volumes:
      - /opt/cds:/data/db
    networks:
      - bdd

networks:
  bdd:
    driver: bridge
